### ISSUE TITLE
Proposing to use a new workflow

### ISSUE THREAD

**Issue by jorge3fernandes** [jorge3fernandes/City_of_Brockton_R#17]
@sconde, I started using [this workflow](http://nvie.com/posts/a-successful-git-branching-model/) for my projects at work and I love it. What do you think about using it for this project?

**Comment by sconde** [comment]
I like this workflow. This is what I'm currently using. Although when I do a PR with your fork, I do it after I've merged into my own master.

There's actually a way to close off your master branch from direct pushes. And the only way to get changes in is through a PR. If you really want to be pedantic with your workflow, you can make sure to have a code review with every PR before a merge.

Is everyone using git at work?

**Comment by jorge3fernandes** [comment]
Not everyone is using it at work. We just hired someone who is experienced in software development and she seems to want to push the team to start using git.

We should get together again to discuss how to manage branches.
